### ISSUE TITLE
Descriptions Can Drop the Last Few Changes When Saved

### ISSUE THREAD

**Issue by LonelyHowls** [DeltaV-Station/Delta-v#1005]
Watch da video

Description: When doing changes to your description text, it can fail to properly record everything that you have typed into the field. This happens after arbitrary periods of time waiting to save the panel (though I haven't waited for more than, like, thirty-ish seconds for this) and happens consistently enough to be annoying.

Reproduction: I've noticed this happen on a couple of rounds so far, but today was the first time that I actually noticed it in play (as I'd usually save my desc after swapping tabs).

(Reposting this to GitHub)

https://github.com/DeltaV-Station/Delta-v/assets/8814763/829e1d1a-51e7-45d6-9bf7-1f3f0309d2b2

**Comment by pissdemon** [comment]
It's an upstream bug and should probably be reported there if you haven't done so yet.

The workaround for now is to just type some junk characters at the end of your description and save so it it deletes the junk instead of your description. If you've got junk left over you can delete some of it and save again until the junk has deleted itself.

**Comment by Axionyxx** [comment]
Upstream issue
