### ISSUE TITLE
some micro issues

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#1320]
## Description
- engi has no tank dispenser for plasma
- none of the external airlocks bolt eachother when opened
- atmos is really tiny and has no direct access to the supermatter area so if you want nitrogen you need to filter distro for it which is cringe

**Comment by Colin-Tel** [comment]
Tank dispenser for plasma:
![image](https://github.com/DeltaV-Station/Delta-v/assets/113523727/44422d21-3fe9-4f8d-bf33-eb55199c92e5)

I haven't gone through the rigamaroo of linking the external airlocks (nor brig timers) because I can't in the mapping tool. I'd need to either wait or do it manually via text editor.

As for atmos concerns, it could be routed via south maints? idk it's not really an issue to me right now with the lack of the SM.

**Comment by deltanedas** [comment]
its a pain in the ass but you can do it by vv disabling access readers
seems like nobody cares about the bug being fixed so thats how it is

**Comment by IamVelcroboy** [comment]
||...About to go make a duplicate issue...||

**Comment by Colin-Tel** [comment]
funny nitro pump
![image](https://github.com/DeltaV-Station/Delta-v/assets/113523727/1f6740cb-caec-4b07-a581-1cb7d2a7c0ed)
