### ISSUE TITLE
Justice department revert discussion

### ISSUE THREAD

**Issue by Axionyxx** [DeltaV-Station/Delta-v#1469]
People don't like the justice department, which is understandable with the way it is implemented. Delta-V doesn't feel like the place that needs it, and this change, while thoroughly discussed both with community members and staff internally before its merge still hasn't turned out quite like was expected.

As such, I personally feel it should be reverted, but I'm making this here so people can both advocate for or against its removal, or suggest alterations that'd make it bearable beacuse lets face it, justice isn't ready for an MRP server like Delta-V.

This is only relevant if we decide to revert it, but the most logical approach would be to remove the new roles, revert lawyer to being lawyer, undo all time alterations and migrate out all justice related items.

**Comment by noctyrnal** [comment]
In my time playing HOS with the justice system, I first was appreciative of it though slowly found it to hold more issues than solutions. Aspects that came with the department were nice, such as the court timer, though the reliance on members of the justice department to handle processing became a nightmare. 

In my eyes, I think an ideal solution would be to grab certain parts from the justice department according to community feedback and then remove the excess and the department itself.

**Comment by Sifb26** [comment]
I’m personally of the opinion that attorney and prosecutor should be merged and the rest be left alone because it can actually help sometimes

**Comment by Axionyxx** [comment]
> In my eyes, I think an ideal solution would be to grab certain parts from the justice department according to community feedback and then remove the excess and the department itself.

I don't think a hard revert is a good idea, as the good changes made will go down with it. But I don't think it should remain in its current state.

**Comment by noctyrnal** [comment]
> > In my eyes, I think an ideal solution would be to grab certain parts from the justice department according to community feedback and then remove the excess and the department itself.
> 
> I don't think a hard revert is a good idea, as the good changes made will go down with it. But I don't think it should remain in its current state.

Absolutely, I feel that this is something we could bring up to a few polls in an announcement to gauge what people want and dont want from the remnants of the justice department.

**Comment by Lyciata** [comment]
This is all my opinion but...

As probably the most common clerk, I have to agree that there are lots of issues with the justice department currently. I think one way of fixing that would maybe fix SoP and Space laws first THEN add the justice department back. There's so many loopholes, not enough explaination and stuff like that. Another thing I would like to say that has not really any link to the revert but more just an opinion. I feel like people shit on justice a lot because we need to be strict about the laws if it isn't our whole reason of a department.

So my opinion the revert would be to fix sop and space laws first and then put justice back personally.

**Comment by BellwetherLogic** [comment]
I'm torn because I really love Justice gameplay and I think it does add a lot to the experience, but it definitely does have some rough edges in practice. I don't think they're as bad as people make it out to be necessarily, but I think a staged addition might have won people over instead of putting it in all at once, ie, introduce court timer, then Pros role and CJ, then the Clerk and the need for evidence submission, etc. 

That said I don't know that rolling it back is the way to go either, since in my (admittedly short) experience things that get rolled back don't tend to return (I'm thinking of revs in particular, though I know there's several competing proposals for how to do that), and I'd hate for that to happen to Justice. The new SOP is a big improvement, and I think more changes like that, with streamlining of processes and cleaning up inefficiencies (Pros not being able to handle evidence directly, etc) would help a *lot*.

**Comment by leonardo-dabepis** [comment]
From what I can tell, there are already people discussing how to fix all of this on Discord in #space-law-rewrite-commitee and I think completely reverting it without their input or without implementing any of the fixes they are working on is unwise.

**Comment by Axionyxx** [comment]
> From what I can tell, there are already people discussing how to fix all of this on Discord in #space-law-rewrite-commitee and I think completely reverting it without their input or without implementing any of the fixes they are working on is unwise.

It has existed for over a month now and almost no changes that actually change anything have been implemented in game. Justice will be disabled if nothing keeps happening.

**Comment by Alyx-Wander** [comment]
> > From what I can tell, there are already people discussing how to fix all of this on Discord in #space-law-rewrite-commitee and I think completely reverting it without their input or without implementing any of the fixes they are working on is unwise.
> 
> It has existed for over a month now and almost no changes that actually change anything have been implemented in game. Justice will be disabled if nothing keeps happening.

The Standard Operating Procedures were updated **three days ago**, specifically to adjust it for the existence Justice Department, which encompassed a near total re-write of it. Most importantly, this re-write amended trial procedures in response to the criticism we'd received over the course of the month.

- Announcement: (https://discord.com/channels/968983104247185448/976726219875831828/1258361013812858902)

- Wiki Revision of SOP: (https://wiki.delta-v.org/index.php?title=Standard_Operating_Procedure&diff=3460&oldid=3454)

We also decided to change aspects of the Justice Department in regards to rules within the last server meeting, which was yesterday.
> ⚒️ - The Justice Department will be held to the same RP standards as Security and Command.

These above changes have had just over half a week to take effect, which hasn't given us enough time to see their effects in a representative way.

As for re-writing Space Law, that is still ongoing and is tracked in a pinned google document within the #space-law-rewrite-committee channel. That has yet to be published because it's a full re-write and the laws play with each other, and so need to be published all at once or else there would be holes. And a minor point of clarification: That channel has existed for a little over 8 months now.

But I don't want you or anyone to only take my word for it. I'll be inviting the rest of the committee here to speak as well as they make up various different areas of expertise.

**Comment by Chromaphasia** [comment]
I've been playing a lot of justice and I think there are two main areas where Justice vs Sec causes some issues. 
-Justice causing security issues due to needing to be able to interact with prisoners, causing escape attempts, assaults, etc.
-Attorneys being annoying, overstepping their bounds outside of what is laid out in the SOP.

I think the first could easily be solved if we had some mechanic to pass items back and forth to prisoners without opening the door (This is also a bit of a skill issue on secs part, they should be able to have enough preparedness to open the door without the prisoner immediately running. In all my time playing Pros and attorney, I haven't seen a flash used once, they usually just resort to chasing the prisoner wildly with a stun/harm baton.)

I think the second issue is less a justice problem, and more an issue between how delta-v handles justice vs SS14 at large. In other servers, being annoying is basically the lawyer's job, they have sec access and little else, so being an obstructionist for their clients is their role. Having some framework for new players to Delta-V get over this old way of doing justice would definitely help. Have something to imply that new attorneys should report to the clerk or CJ to learn the ropes. You wouldn't blame engineering as a department for engineering assistants running around and 'fixing' things, just because the new players don't know what to do.

As mentioned previously, there was also a large change to the way Justice and Security interact that has barely had a week to operate, and it should do a lot for letting Sec operate in the absence of a (good) prosecutor. All in all, I think the biggest issues with Justice come from bad/unknowledgeable players, not the department itself, it just needs a better framework for teaching new justice players outside of telling them to read the SOP and space law wiki pages, but no, not the SS14 one, the Delta-V specific wiki pages.

**Comment by ThataKat** [comment]
I like the idea of justice a lot (as a sec player) it just seems to have some technical challenges. I haven't played much since its implementation so I am working on limited data but here's what I've observed so far.

Prosecutor is an excellent idea and takes a lot of weight off sec, if they're efficient. I like not having to worry so much about sentencing as a Warden or officer, and just being able to describe the crime to justice and have them handle it is nice. However, I have encountered times where I still know much more about law/SOP than the Pros. and end up having to make the sentencing myself anyways.

Attorneys seem fine to me so far, but sometimes lost as to what their job is. Sometimes just defaulting to a replacement Pros. when there is none. I think the concept is good, but again have had interactions where justice members seem a bit deer-in-the-headlights and I have to guide them through the process as a sec member (namely in paroles for permas). Which kind of defeats the point for me.

I haven't read up on new trial procedure, but the one trial that we attempted to have under my care as Ward still took an extremely long time to get going. The entire process was left to justice who still seemed to struggle with making it timely. So trials still seem to be a trouble spot.

Overall Justice seems good in concept for the most part right now, it just lacks the experienced players (or players at all often) to be a boon and not just extra bureaucracy that slows down sec. A department revert could be done I suppose, but a lot of the ideas seem really helpful if executed properly.

**Comment by BellwetherLogic** [comment]
> I think the second issue is less a justice problem, and more an issue between how delta-v handles justice vs SS14 at large. In other servers, being annoying is basically the lawyer's job, they have sec access and little else, so being an obstructionist for their clients is their role. Having some framework for new players to Delta-V get over this old way of doing justice would definitely help. Have something to imply that new attorneys should report to the clerk or CJ to learn the ropes. You wouldn't blame engineering as a department for engineering assistants running around and 'fixing' things, just because the new players don't know what to do.

This is why I think we need a new role, Paralegal, to be the training role for Justice. I've hired Paralegals once or twice as Clerk but having a dedicated Learn How To Space Law role might help emphasize that Attorney isn't just a Be A Tider With Brig Access role on Deltav.

**Comment by ghost** [comment]
> > From what I can tell, there are already people discussing how to fix all of this on Discord in #space-law-rewrite-commitee and I think completely reverting it without their input or without implementing any of the fixes they are working on is unwise.
> 
> It has existed for over a month now and almost no changes that actually change anything have been implemented in game. Justice will be disabled if nothing keeps happening.

To interject from someone who's been overseeing all of this;
Space Law Rewrite, that inherently is going to take forever because they're trying to weed out all the loopholes. I'm waiting until they get it into a shape where it's decent with the new additions so we can finish up and other things with it can get fixed after the fact.
Justice is going to be hard to revert (doable though!) because it's extensively been mapped. 

Overall I think Justice, Space Law and the understanding of it here needs to be straightened out and re-evaluated if we want things to work. Space Law, SoP and Company Policy need to be more accessible in game for newer players (I hate them having to go to our old ass wiki, that's like. Grr. Wiki maintenance is another can of worms because I'm basically the guy soloing it at this rate.) and I think we need to straighten out the perception of what it's supposed to be on here vs how it is elsewhere. I dunno. It's confusing, and what I'm saying might not be entirely coherent.

**Comment by Timemaster99** [comment]
I'm one of the contributors on the Justice PR, alongside Velcro, Blue, Leo, and Alyx. We've been thoroughly involved in plotting out Justice's place and dynamics, so perhaps we can offer some different perspectives. I want to bring up some of the following

1. From the polls and my experience, Justice isn't overall _hated_. The issues it had at its epoch were primarily its intrusion into security gameplay (which is mixed in opinion) and playtime farming. I worked to push SOP changes out quickly to get Justice's reach out of sec for the most part. The response to the poll wasn't necessarily positive, however, and therein lies one of the issues presented next.
2. Some roles in Justice are boring. This should not be misconstrued; I don't think lawyer roleplay is boring to its playerbase. Rather, I think the roles that we chose and the responsibilities we gave them lack in substance. Justice was originally organized with 3 lawyers, a Clerk, and a Chief Justice. The Clerk would manage the lawyers, the lawyers would manage sentencing, and Chief Justice would handle judging. As we slowly molded the department, we tried to keep the original shape, but some of these roles are current issues. Clerk has a job that's too nebulous and lacks substance, in essence being Chief Justice Lite while Chief Justice has _nothing_ to do except wait for a trial.
3. The SOP changes have yet to be tested. I do not think the SOP is a cure-all, but through it, Justice's obstruction of security has been drastically reduced. This department is heavily dependent on text to define its role, so changes will not be seen on the repo nearly as much. Players need time to read SOP and commit it to memory before this has a noticeable effect.

As for solutions, I believe there are a few options. In descending order of intensity:

1. Write Wiki pages for the jobs and directly announce it to players. I think this should be done regardless of the solution, since those pages give players _direction_ in which to take the role.
2. Increase security playtimes on Justice roles, which is another that should apply regardless. The lack of SOP knowledge is crippling, and given its power over security, it should have a _notably_ high bar of entry.
3. Remove Clerk and merge it with Chief Justice. I do not think the Clerk has a role inside this current Justice department, and the responsibilities should be given to CJ instead to give them more to do.
4. Remove Prosecutor, have 3 lawyers under Clerk, and CJ above them. This is the original version. These three lawyers can either all have authority over sentencing, or have none and simply work to advise sec or crew at the Clerk's assignment.
5. Remove Prosecutor and Clerk, remove the department, keep CJ as a special command role and return Lawyer to service. This outlook is inspired by Paradise (ss13), which has a singular Magistrate in command and directs Internal Affairs Agents (SOP inspectors, basically) to investigate SOP and legal infractions. We can choose to add this Internal Affairs Agent, or keep Lawyer, while CJ acts as a final authority on Space Law and judge.

All things considered, we need to wait for new SOP to go into effect before enacting the more sweeping changes. The SOP rewrite is indeed an _in-game change_, and I believe it is misinformed to revert the entire department over criticism that has been addressed in these changes. I will, however, still be looking out for more ways to improve the experience here.

**Comment by Timemaster99** [comment]
> This is all my opinion but...
> 
> As probably the most common clerk, I have to agree that there are lots of issues with the justice department currently. I think one way of fixing that would maybe fix SoP and Space laws first THEN add the justice department back. There's so many loopholes, not enough explaination and stuff like that. Another thing I would like to say that has not really any link to the revert but more just an opinion. I feel like people shit on justice a lot because we need to be strict about the laws if it isn't our whole reason of a department.
> 
> So my opinion the revert would be to fix sop and space laws first and then put justice back personally.

Could you specify the loopholes and issues with SOP? These are things we'd like to address

**Comment by deltanedas** [comment]
i think folding clerk into cj would be good since managing the court timer is a non-job and cj is someone youd expect to notarize documents and warrants anyway

attorney as a "sec the clown did nothing wrong" is generally useless and in a trial anyone can defend people anyway, so being combined with prosecutor as general knows-the-law would benefit. also when sec is overworked more than 1 person doing prosecutors duty helps so there arent 3 people sitting in a cell while 1 has your full attention

**Comment by IamVelcroboy** [comment]
(Just going to copy/paste the report I left in the space law rewrite channel.)

**Issues the JD set out to solve:**
- Holding court was a mess. 
- Getting everyone necessary to the courtroom took ages
- HoS, Captain, and other heads needed for the hearing would constantly be distracted and pulled away from court by the radio or emergencies
- HoS, Captain, other heads needed for the hearing, and arresting officers pulled away from their standard duties leaving other tasks/station safety to fall behind
- Create some oversight to security mishandling authority

**Issues the JD has solved:**
- HoS, Captain, and other heads are no longer burdened with trials
- Security is no longer burdened with trials.

**Issues the JD has partially solved:** 
- Oversight of sec through prosecutor is good but sometimes goes too far

**Issues the JD has created:**
- Security is now burdened with arguing many sentences with the prosecutor
- Security and prosecutor seem to be at odds with one another as opposed to being cohesive links in the justice chain
- Trials are just as long/or longer due to confusion, or lack of optimization
- Getting evidence organized and to trial takes ages and is hard to coordinate with detective

**Issues related to Sec/JD not really related to JD but brought to light as a result:**
- Security players are frequently setting and waiting for cell timers before returning to patrol. A job that clearly belongs to warden/guards but warden/guards are often too preoccupied with perma residents.
- Perma has become a luxury spa with warden/guards acting as the wait staff. While this is an issue in itself, it directly affects the rest of sec and JD.

**Possible solutions:** 
- Add guards to every station and task them with setting and monitoring cell timers
- Address prisoner expectations (guards/warden are not their errand runners)
- Give evidence lockers prosecutor/clerk access and/or create a new “evidence box”)(PR in progress)
- Return felony sentencing to sec/attorney deliberations unless defendant maintains innocence and asks for a trial (Already in place)
- Merge warden and guards into JD making it so JD is entirely responsible for carrying out sentencing and releasing prisoners (What do about armory?)
- Move some workload form prosecutor onto clerk. (Prosecutor should never have to leave a trial in progress or be distracted by 2 cases at the same time.)
- Trials reduced from 25 mins to 18
- Obviously, create SoP/spacelaw guidelines that better streamline and detail the trial(pre-trial) procedures(WiP)

**Final thoughts/Ideal vision:**
RP is the name of the game. This is a new (and imo, fantastic) tool to facilitate RP on the station. However, players seem to be getting hung up on unclear rules, procedures, and mechanics.

**Ideals:**
>Misdemeanor: Sec makes arrest-> Sec sets sentence according to SoP-> Defendant has option to request an attorney but these should almost never go to trial. Either way, sec returns to duty as soon as sentence is set. If there is further arguments to be had, sec makes a statement to pros and argument is between pros(clerk if pros is preoccupied)/attorney. 

>Felony: Sec makes arrest->Sec reports crime/details/sentencing recommendation to prosecutor or clerk and attorney->Sec returns to duty->Prosecutor (clerk if pros is preoccupied) deliberate with defense attorney either confirming or denying original sentence or adjusting it. Trial is only necessary if defendant maintains innocence, or pros/attorney cannot reach an agreement. 

>Capitol: Sec makes arrest->Sec turns in evidence and makes statement to pros->sec returns to duty->Defendant is turned over to attorney->when both sides are ready a trial begins.

- In all cases a sentencing should be carried out by the warden and guards. 
- In many cases detective should begin collecting evidence before an arrest is made even, to secure a warrant, and to prepare for trial. 
- In cases where that’s not possible (security needs to arrest someone posing an immediate danger to the station/crew) detective should coordinate with arresting officer as soon as possible to secure evidence and run analysis. 

- More RP based trials should be encouraged through the player base to create more action in the courtroom. Lawsuits, ambulance-chasing attorneys, possession disputes, etc. This isn’t easy since we don’t have much in the way of settling them (ie: economy) However, we are an RP-based server and this is fertile ground for great RP if we can get players to play along.

**Comment by IamVelcroboy** [comment]
**Since it's mentioned a few times, Reasons prosecutor should not be merged with lawyer.**

- Conflict of interest. The purpose of prosecutor is to take the statement from security and be their representative in court. The lawyer is the exact opposite of that, representing the accused. If we have the same role flip/flopping and not clearly defined, how can they be trusted to represent the party they are meant to represent. Why would a sec officer turn over evidence/statements/etc to the player that might or might not be using that against them in court? 

- Confusion. Too many times before the JD was introduced, some players simply did not understand who they were supposed to be representing. Since they were Nanotrasen employees, they thought they were *supposed* to be getting antags sentenced to harsh penalties as opposed to the opposite of getting them the lowest sentence possible. Having a defendant role and prosecutor role defined at the start of the round clears that up.

**Comment by IamVelcroboy** [comment]
> This is why I think we need a new role, Paralegal, to be the training role for Justice. I've hired Paralegals once or twice as Clerk but having a dedicated Learn How To Space Law role might help emphasize that Attorney isn't just a Be A Tider With Brig Access role on Deltav.

That's an interesting idea for sure

**Comment by Timemaster99** [comment]
> **Since it's mentioned a few times, Reasons prosecutor should not be merged with lawyer.**
> 
> * Conflict of interest. The purpose of prosecutor is to take the statement from security and be their representative in court. The lawyer is the exact opposite of that, representing the accused. If we have the same role flip/flopping and not clearly defined, how can they be trusted to represent the party they are meant to represent. Why would a sec officer turn over evidence/statements/etc to the player that might or might not be using that against them in court?
> * Confusion. Too many times before the JD was introduced, some players simply did not understand who they were supposed to be representing. Since they were Nanotrasen employees, they thought they were _supposed_ to be getting antags sentenced to harsh penalties as opposed to the opposite of getting them the lowest sentence possible. Having a defendant role and prosecutor role defined at the start of the round clears that up.

This is why I believe making job pages and some better guides for each of the Justice roles will help. These roles are abstract in nature and need extra definition

**Comment by IamVelcroboy** [comment]
> This is why I believe making job pages and some better guides for each of the Justice roles will help. These roles are abstract in nature and need extra definition

Oh shit, the wiki pages never got made for them?!? I swear I bugged someone to do it... Yeah, those should be added ASAP

**Comment by Chromaphasia** [comment]
To respond to some earlier points:
I think merging Clerk into CJ makes sense. However, I disagree that Attorney and Pros should be merged. Having concrete pros/attorney roles makes sense to me, and it means that players can join a server as one or the other and know what their signing up for and what will be expected of them. Merging the roles means that in order to play 'Lawyer', you have to know ALL the procedure, pros and defense, which is a lot for a new player, especially with no 'teacher/learner' roles clearly defined. I think making it two max attorneys and two max pros would help, instead of the current ratios. Also, merging pros and attorney runs the risk of getting 3 players who want to all be pros-type lawyer, or all attorney-type lawyer, and having 3 pros or 3 attorney in sec at one time is definitely too much, and having to make the CJ force one of them into being pros or attorney prooobably won't be super enjoyable for that player for that shift, especially if they really wanted to play one or the other.

Edit: I wanted to add that while I like the idea of the Paralegal role for new players to learn how to play justice, I think adding it would mean needing to remove some attorney/pros slots because, again, more than 3 justice personnel in the brig at one time and it starts to be a bit too much. Having two attorneys, a pros, and a paralegal hanging around might be a large crowd. ESPECIALLY on slow/non-humanoid crisis rounds where sec gets like... one random clown arrested repeatedly the entire shift and no one else. 4 *bored* justice players waiting for something to happen, all hanging around sec, its not going to go well for sec or justice I feel.

 Edit 2: If we do add Paralegals, I think it should be 1 pros, 1 attorney, and 2 paralegals. That way, with all slots full, pros and attorney can pick a paralegal to be their understudy, and if the slots aren't all full, there's flexibility there. If there's no paralegals, then its just like any other shift with low staff, but at least you know that the justice people *should* know what they're doing, unlike how it is now where you don't know if your pros is super experienced or just unlocked the role and needs to be taught. If its *just* paralegals, then CJ/sec knows they need to be taught before they can be trusted to be promoted to a pros or attorney to fill in that shift.

**Comment by ps3moira** [comment]
The justice department spread thin the gameplay for security to the point it doesn't feel fun to play security. I made a post explaining some more points. Honestly, I get why some people might like the idea of it but it just generally doesn't fit with the game and stations job ecosystem.

Here's some points I made on the discord wyci for a revert suggestion

Poor Gameplay
Security's purpose and gameplay were stretched very thin for this department to have any gameplay value, to the point that playing sec is a headache and 30+ minute court sessions still occur. The justice department is not a necessary department for the station ecosystem to run normally, compared to every other department, and it was running fine with just the security department. Warden and HoS are hurt a lot by the Justice Department, and the argument that "more free time to do whatever" as a HoS/Warden translates to less gameplay for them in interacting and dealing with convicts and doing their original job.

Intentions Executed Poorly
The intention was to give some more power to lawyers so they have more importance and space law is more present and stop 30+ minutes trials. This wasn't really an issue with sec law being more or less present, but people weren't caring about lawyers too much. While space law is important, having an entire justice department on a science-based station doesn't make sense especially if it's to give lawyers more importance. It's even more of a struggle on stations with little to no lawyers, and sec can't do their original job, and vice versa for lawyers. 

20/20 hindsight of course a department's main gameplay value that's supposed to last 10-15 minutes max would be extended and players would try to have a court session at least once or multiple times a 2 hour shift just so they can do something in that department.

Also worth mentioning that the PR was somewhat biased in design to make lawyers a big part of the game because it was made by a lawyer main.

**Comment by ps3moira** [comment]
Also worth mentioning that the PR was somewhat biased in design to make lawyers a big part of the game because it was made by a lawyer main.

**Comment by leonardo-dabepis** [comment]
> The justice department spread thin the gameplay for security to the point it doesn't feel fun to play security. I made a post explaining some more points. Honestly, I get why some people might like the idea of it but it just generally doesn't fit with the game and stations job ecosystem.
> 
> Here's some points I made on the discord wyci for a revert suggestion
> 
> Poor Gameplay Security's purpose and gameplay were stretched very thin for this department to have any gameplay value, to the point that playing sec is a headache and 30+ minute court sessions still occur. The justice department is not a necessary department for the station ecosystem to run normally, compared to every other department, and it was running fine with just the security department. Warden and HoS are hurt a lot by the Justice Department, and the argument that "more free time to do whatever" as a HoS/Warden translates to less gameplay for them in interacting and dealing with convicts and doing their original job.
> 
> Intentions Executed Poorly The intention was to give some more power to lawyers so they have more importance and space law is more present and stop 30+ minutes trials. This wasn't really an issue with sec law being more or less present, but people weren't caring about lawyers too much. While space law is important, having an entire justice department on a science-based station doesn't make sense especially if it's to give lawyers more importance. It's even more of a struggle on stations with little to no lawyers, and sec can't do their original job, and vice versa for lawyers.
> 
> 20/20 hindsight of course a department's main gameplay value that's supposed to last 10-15 minutes max would be extended and players would try to have a court session at least once or multiple times a 2 hour shift just so they can do something in that department.
> 
> Also worth mentioning that the PR was somewhat biased in design to make lawyers a big part of the game because it was made by a lawyer main.

This is only addressing the final sentence of your comment. I wasn't the main person who worked on the gameplay and mechanics of that PR. I handed the PR over to velcroboy and timemaster, both of whom aren't lawyer mains to my understanding, after I stopped being involved with DeltaV and I realized I couldn't do all that work on my own even if I wanted to. Realistically, all I contributed to the PR was sprites, so saying that the PR was biased because of me is a bit odd.

**Comment by MilonPL** [comment]
No we are not reverting justice.
