### ISSUE TITLE
something should be done with energy shotgun

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#1667]
## Description
some ideas floated:
- give hos the energy shotgun and move x-01 to wardens locker
- the reverse, energy shotgun to warden
- 50/50 shotgun and laser in spawner, make steal target use the same group and have it just be hos' energy weapon
- both for hos :trollface:

**Comment by Avalon-Proto** [comment]
I vote for either both go to HoS and they can decide to give one to warden. Or warden gets the X-01 as it is a more compact weapon better suited to dealing with possible prisoner riots. And then HoS has their super shotgun for dealing with other threats and targets

**Comment by IamVelcroboy** [comment]
The idea I had was we randomize it in HoS locker 50/50

**Comment by Avalon-Proto** [comment]
> The idea I had was we randomize it in HoS locker 50/50

Both being available would be nice though. And also if we only had one or the other in a round, what happens if someone rolls the objective for the one not in game? Probably safer to have both open

**Comment by deltanedas** [comment]
its possible to make the objective work by giving both items the same steal group

**Comment by Radezolid** [comment]
From my point of view, warden having the energy shotgun makes more sense.

Warden having the shotgun is good due to:
- Big inventory space or use of suit slot which doesn't matter that much since Warden rarely leaves the brig.
- They usually have to fight close quarters due to them being in security.
- Good for protecting armory.
- They already have the kit baton + flash + flashbangs if prisoners riot when wielding isn't viable.

Meanwhile HoS should be more viable with the multiphase due to:
- One handed and pocketable.
- Can shoot throught windows.
- Variable range since you don't have to worry about the spread.

I want to point out I have not played neither Warden nor HoS, but this is my opinion after watching both fight across rounds.

**Comment by Radezolid** [comment]
Question, two months after this issue was opened, any conclusion made? I would love to see the shotgun in game.

**Comment by Radezolid** [comment]
Something was done

**Comment by Stop-Signs** [comment]
YAY i fixed an issue that i didnt know existed
