### ISSUE TITLE
Space friction changes

### ISSUE THREAD

**Issue by sleepyyapril** [DeltaV-Station/Delta-v#1698]
## Description

The space friction changes need to be reverted or changed, because I literally got thrown out an airlock and I was still moving through space 15 minutes later.

**Reproduction**

Get thrown out an airlock
You'll be still going for a whiiile

**Screenshots**

N/A

**Comment by deltanedas** [comment]
you can throw items behind you

**Comment by sleepyyapril** [comment]
> you can throw items behind you

I was dead, it's too powerful for disposing bodies. 0 chance of saving them

**Comment by deltanedas** [comment]
even with old friction throwing a body into space is more or less guaranteed to RR them since they arent visible on crew monitor

**Comment by sleepyyapril** [comment]
> even with old friction throwing a body into space is more or less guaranteed to RR them since they arent visible on crew monitor

but this is 0 chance, thousands and thousands of units from station if let go long enough

**Comment by Avalon-Proto** [comment]
> > even with old friction throwing a body into space is more or less guaranteed to RR them since they arent visible on crew monitor
> 
> but this is 0 chance, thousands and thousands of units from station if let go long enough

I mean, that's just how space works. There is 0 friction in space so you'll just keep flying and flying forever. Most corpses that get chuckled out an airlock were irrecoverable without admin intervention anyways

**Comment by jimmy12or** [comment]
As someone who has fallen victim to this as well, I will say that Yes, it's a near guarantee of being round removed, I can also agree that this also makes sense from a physics standpoint. So the question more comes down to, Do we want space to be more forgiving, or more realistic? While it sucks to have that happen, I think space being realistic is better since that's one of the main threats of living on a space station in the first place. That's why the nerf from upstream to pressure damage was removed as well. (I think that's why anyways.)

**Comment by Tmanzxd** [comment]
Wizden removed space pens then was surprised that people were dying to spacing a lot then they nerfed space.

I've been victim to Space Wind as well, but I don't think this PR is needed. If you get yeeted like this you can do any of the following:
- Throwing items behind you
- Fire extinguisher
- aHelp and ask staff to send your coordinates to the crew 
- Wear magboots
- Split items up from stacks to throw behind you

There is so many options and I agree with the others that the realism of the physics matters more tbh.

**Comment by Lyndomen** [comment]
> Most corpses that get chuckled out an airlock were irrecoverable without admin intervention anyways

FWIW, Admin policy is to not save these players who were intentionally round removed by an antagonist.

**Comment by sleepyyapril** [comment]
I'll reiterate my point is when you are already dead.

**Comment by IamVelcroboy** [comment]
Space is dangerous

**Comment by Samsterious** [comment]
I have been victim to this myself (kill target), and I did not understand at the time that space friction had been removed. Several of my peers knew that I had been lost to space and acquired the help of Logistics to send a shuttle out to search for me. I thought the parallax drift was just the clouds on Glacier animating. I later ghosted and realized I was insurmountably far from the station and that all of their efforts were for naught.

On one hand, I feel very "Them's the breaks!" about it. On the other, they spent thirty minutes searching for me with a shuttle and never stood a chance. But then, back to the first hand, I have often searched for people alive and really quite close to the station and do not find them most of the time. Space is big, even _with_ space friction.

I am of the opinion that the removal of space friction is consistent with the physics one _expects_ from space, and that it is a player issue if antags are using this mechanic flippantly (i.e. high-quality syndies should leave your body somewhere it could still _possibly_ be found; hide it, rather than round-remove you). As for tripping out an airlock, there are some cases where an AHelp is warranted (i.e. lag-induced death) and some where, yes, you do just irreconcilably lose sometimes. From a game direction standpoint, I am inclined to consider this issue "Not A Bug".

**Comment by ghost** [comment]
Given the unanimous consensus among a few players, contributors, and some staff that this issue is a non-issue and not a bug, I'm gonna close this. I'm sorry, but them's the breaks - space is cruel and unforgiving and you can get thrown and go for miles.
