### ISSUE TITLE
Admin right click options broken after new update (forked server)

### ISSUE THREAD

**Issue by progamer12312369** [DeltaV-Station/Delta-v#1894]
## Description
Issue involving most admin right click options such as: Antag, Debug, Admin, Tricks, Smite.
All options other than debug > export sprite have vanished after merging latest delta v update into fork

**Reproduction**
Fork delta v, add custom music, merge latest updates, admin right click options vanish

**Screenshots**
Unable to get, menu closes after screenshot

**Additional context**
Delta-V forked server, fork is mainly just custom music.

**Comment by ghost** [comment]
Happened on the main server as well; the upstream merge seems to have irrevocably fucked all verbs, which is why this is tagged "Upstream Issue."
You cannot:
- Butcher things
- Change your instrument as harpy
- Do any admin verbs
- Can't use chameleon clothing
- Anything else that requires a verb to function, essentially.

No logs are left. Milon has told me that there was a change to the verb system, we're looking at what broke it currently.

**Comment by MilonPL** [comment]
https://github.com/space-wizards/space-station-14/pull/23427 broke it
![image](https://github.com/user-attachments/assets/355ffef5-2e67-40eb-ad91-4fc55ef57f62)
my guess is that the state isn't set properly, works in mapping when it shouldn't, and vice versa

**Comment by ghost** [comment]
In that case, might wanna redo the upstream merge that pulled this, and trigger a publish again. Or fix it manually.

**Comment by MilonPL** [comment]
> In that case, might wanna redo the upstream merge that pulled this, and trigger a publish again. Or fix it manually.

@deltanedas plz fix

**Comment by MilonPL** [comment]
https://github.com/DeltaV-Station/Delta-v/pull/1895
