### ISSUE TITLE
all the gamemodes kinda suck

### ISSUE THREAD

**Issue by Lyndomen** [DeltaV-Station/Delta-v#2133]
## Description
Individual events are mostly fine, but rounds become routine when you sus out what type it is with gamer sense

**Reproduction**
Play game for 2000 hours

**Screenshots**
How would this be relevant

**Additional context**
Discuss here, don't dare do it on draft

**Comment by Lyndomen** [comment]
Fuck randy random, we Cassandra classic

**Comment by HTMLSystem** [comment]
I disagree heavily. Survival gets chaotic, yes, but you don't know which events will happen. Extended is nice because it's just more manageable survival, a chance to do bigger projects while still being able to go off of the game events. Greenshift is nice to just have a chill time and focus more on rp. Secret can be interesting because of the prospect of traitors or nukies. Especially if you play on peri and kinda know what you're getting so you don't have to "sus out" what gamemode it is half of the time. There's still a lot that could happen!!
