### ISSUE TITLE
Vent critters 

### ISSUE THREAD

**Issue by Lyndomen** [DeltaV-Station/Delta-v#2425]
## Description
Too often, and too shit 

**Reproduction**
Play survival 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 
VENT CRITTERS 

**Screenshots**

**Additional context**

**Comment by Lyndomen** [comment]
How do we fix the event to not be shit

**Comment by therealDLondon** [comment]
Reduce the weight of VENT CRITTERS, which just means we'll get more "ABNORMAL ACTIVITY DETECTED IN THE STATIONS POWERNET"
It doesnt help theres like 6 different vent critter events

**Comment by Lyndomen** [comment]
> Reduce the weight of VENT CRITTERS, which just means we'll get more "ABNORMAL ACTIVITY DETECTED IN THE STATIONS POWERNET" It doesnt help theres like 6 different vent critter events

I'd rather play in the dark for 2 hours than fight the 17th wave of funny green slimes

**Comment by Lyndomen** [comment]
> Reduce the weight of VENT CRITTERS, which just means we'll get more "ABNORMAL ACTIVITY DETECTED IN THE STATIONS POWERNET" It doesnt help theres like 6 different vent critter events

It's always back to enabling the immovable rod

**Comment by therealDLondon** [comment]
if direction approves the rod I will add the rod back RIGHT NOW

**Comment by rosieposieeee** [comment]
reduce the weight and make it far less likely to just shit out a bunch of harmless mobs that add nothing to the game

**Comment by Lyndomen** [comment]
Mothroach and mice mains seething

**Comment by Monotheonist** [comment]
> reduce the weight and make it far less likely to just shit out a bunch of harmless mobs that add nothing to the game

That would implicate making more events (to reduce this weight) that aren't just random harmless mobs which would be very WYCI, as well. I only mention that since Fox said that we'd get more Abnormal Activity :tm: and Immovable Rod :tm: .
What comes to mind for WYCI for that stuff (that isn't More Shuttle Events or More Antags) is like,
- Carp migration (carps on the outside of the station and other tiers of it involving various space fish. Not sure what the logistics of coding this would be like. Might require mapping spawners on station shielding which would be a time.)
- Camera failure (breaks one of the cameras, should be a nuisance to the AI, but not too
- Rampant brand intelligence (Technically, this already exists as an upstream event but it's turned off because it also effects the vending machines on Central Command and creates ten billion "nothing" ghostroles, as well as it not being too fleshed out IMO)
- Disease breakouts that AREN'T zombies (requires newmed or virology)
- Space colors (described as going through a molecular cloud, hueshifts the color of the parallax is all you'd probably need for that and it probably wouldn't work with glacier. Alternatively this could be something like space dust, as well)

**Comment by Monotheonist** [comment]
Oh, we can also send spam to the captain and everyone else now now with the advent of PDA messaging. That's another event scheduler WYCI idea.

**Comment by sleepyyapril** [comment]
Lower the _number_ of vent critters so it's less impactful.

**Comment by Nairodian** [comment]
I've had a couple ideas to alleviate this for a while for other servers, just never written it down.


Roll all the vent critter events into one gamerule that chooses from a list of mobs to use, like it has access to slimes, mice, spiders, etc, etc. But when it starts it rolls to pick one or one _group_ of mobs. (Groups sound even harder to do, but I think would be the best option. So you'd have like all the mice grouped into one, the different types of slimes, snakes, spiders, etc.)

---
Another way to make the event more interesting, is to make it only affect a certain area instead of station wide. So instead the gameule finds a single random vent to use, then you get an announcement that goes something like, "We have detected a number of life forms nesting in the vents near [Nearest Station Beacon To Said Vent]," and then after a small delay all nearby vents to the selected vent in like a 15-30 tile radius spawn the selected vent critters.

The more random aspects you can include, the better I think. Like maybe rarely it _is_ still station wide. Or sometimes it doesn't announce where the critters were located. And even maybe throwing the crew a bone and specifically calling out what type of critters are spawning.
