### ISSUE TITLE
Borgs keep scottish accent

### ISSUE THREAD

**Issue by UnicornOnLSD** [DeltaV-Station/Delta-v#615]
## Description
When you choose to be a borg certain accents stay on no matter what, which is kinda off since borgs have positronic brain and well, aren't a person.

**Reproduction**
Pick a character, turn on scottish accent
Spawn as borg, speak and you are scottish still.

**Screenshots**
![image](https://github.com/DeltaV-Station/Delta-v/assets/149102472/28d2d8fe-2e8e-402a-b364-476b3ed07dbb)

**Additional context**
it's kinda funny but still a bug so fix it or not here it is

**Comment by DangerRevolution** [comment]
This is an issue with every trait, only fixed with nearsighted iirc

**Comment by Adrian16199** [comment]
The best way to prevent these types of traits going to the borg would to make a system that parkstation has that would not allow most if any traits to be on the cyborg instead of what I did, basicly a bandaid fix by whitelistin the trait which wont fix any other trait. Im not sure if an accent really is an issue compared to the 2 traits that either make you fully blind or not be able to move but I understand the concern.
