### ISSUE TITLE
Laika ear slot should be removed

### ISSUE THREAD

**Issue by DebugOk** [DeltaV-Station/Delta-v#625]
## Description
It just incentives Laika to beg for cognizine, that along with the ID slot, and the ability to pull means Laika can go hunt people down solo. The ID card slot might also be on the chopping block, as its literally a dog.

With punpun, at least its a monkey, so it somewhat makes sense.

**Comment by DangerRevolution** [comment]
+1 for removing ear slot; Laika should be *reliant* on Security rather than a part of it IMO. It seems atm Laika is pretty much just an extra officer on the roster rather than it's companion.

**Comment by ps3moira** [comment]
I thought it was kind of funny to talk on security radio and just hear, "Woof". I'm ok with ear-slot being removed for Laika though.

**Comment by BramvanZijp** [comment]
I feel like theres no major reason to remove them. If its abused in-round, which I have not seen happen, you can simply remove or not give the headset untill an AHelp is answered. But as I said, I havent seen any issues come from this. But I do also understand laika should probably not be going out solo (Something I have found myself guilty of due to the info provided to me by people chatting on radio.), so in that regard it would make sense to remove it, but the ID is fine imo.

**Comment by leonardo-dabepis** [comment]
I support the ear slot getting removed. Plus Laika doesn't even have a headset sprite, so the headset just floats above her. I also think the ID should be removed because, like what DangerRevolution said, Laika should be reliant on security because she is a dog, not an officer.

**Comment by BramvanZijp** [comment]
While that is true, the lack of an ID does make it a lot more annoying to play laika both for sec and laika herself, as she has to repeatedly ram into a door untill an officer notices and lets her through, which just gets tiring after a while. I feel like the lack of a headset should be enough to more encourage laika to play with an officer.

**Comment by Guess-My-Name** [comment]
We already have monkeys without cognizine that are played just like mute humans with one hand.
Laika having a headset incentivizes Laika players to respond to calls on radio (because why would a dog be given a radio if that wasn't the desired result), and combining it with ID slot, just like DangerRevolution said above, it just makes her another officer that simply can't speak or write.
Definitely +1 for the headset removal, id should be gone too, Laika shouldn't be an exception among pets.

**Comment by DebugOk** [comment]
Laika is a pet, not a security officer. It having either doesn't make much sense.
