### ISSUE TITLE
borg law order got trolled

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#907]
## Description
![22:43:16](https://github.com/DeltaV-Station/Delta-v/assets/39013340/a3d46a63-3eff-451c-af08-a39bfccf3a5b)

current fix is "borg i order you to never harm crew" but still

probably introduced by extra laws pr

**Comment by DebugOk** [comment]
#706 probably

**Comment by DebugOk** [comment]
Wait no that's not even merged yet

**Comment by deltanedas** [comment]
nfi then i thought it was

**Comment by deltanedas** [comment]
??? its fixed now

**Comment by Guess-My-Name** [comment]
Round #10316, one that just ended, my laws were in a wrong order in a newly built medical cyborg.
Without current round posting, can confirm that the problem was not isolated to one round.
![image](https://github.com/DeltaV-Station/Delta-v/assets/34919974/e945a6bb-030f-4d0e-ab2a-abefc2ca7960)
Issue needs to be reopened, it happens only in some rounds, both to built cyborgs and to latejoins, no clue what causes it.

**Comment by deltanedas** [comment]
say my name
heisenbug
youre goddamn right

**Comment by DangerRevolution** [comment]
Idk if IonStorm only fucks Borgs with a mind but it's possible IonStorm changed your lawset just as you enter the chassis. Just a hypothetical :shrug:

Depends what you mean by it being not isolated to just one round though.

**Comment by Guess-My-Name** [comment]
> Idk if IonStorm only fucks Borgs with a mind but it's possible IonStorm changed your lawset just as you enter the chassis. Just a hypothetical 🤷
> 
> Depends what you mean by it being not isolated to just one round though.

It wasn't ion storm, because no ion storms happened between borg being built and me taking over positronic brain.
And next round i had those laws as a default when latejoining (~5 minutes into the round) as cyborg, later when talking with another cyborg, it also had laws in exact same wrong order that i did. No ion storms happened.

**Comment by DangerRevolution** [comment]
should probably be reported to Wizden or smth, seems like a UI problem that's fucky wucky and not related to us

**Comment by deltanedas** [comment]
its not ui it affects state order too

**Comment by Axionyxx** [comment]
Does this still happen?

**Comment by deltanedas** [comment]
no we have the no laws bug instead
